package com.hlms.workflow.origination;
public enum OriginationEvent { CREATE_APPLICATION, UPLOAD_DOCUMENTS, VERIFY_KYC, COMPLETE_CREDIT_CHECK, COMPLETE_VALUATION, COMPLETE_UNDERWRITING, APPROVE, REJECT, SEND_BACK }
