package com.hlms.workflow.origination;
public enum OriginationState { LEAD_CAPTURED, APPLICATION_CREATED, DOCUMENTS_PENDING, KYC_VERIFIED, CREDIT_CHECK_COMPLETED, PROPERTY_VALUATION_COMPLETED, UNDERWRITING_COMPLETED, PENDING_APPROVAL, SANCTIONED, REJECTED }
