package com.hlms.common.util.enums;
public enum DisbursementStatus { PENDING_AGREEMENT, AGREEMENT_SIGNED, PRE_DISBURSEMENT_CHECK, APPROVED_FOR_DISBURSEMENT, DISBURSEMENT_INITIATED, DISBURSEMENT_COMPLETED, PARTIALLY_DISBURSED, FULLY_DISBURSED, FAILED, CANCELLED }
