package com.hlms.common.util.enums;
public enum Role { BRANCH_OFFICER, BRANCH_CREDIT_OFFICER, BRANCH_MANAGER, REGIONAL_MANAGER, ZONAL_MANAGER, CENTRAL_CREDIT_COMMITTEE, COLLECTION_OFFICER, COLLECTION_MANAGER, SYSTEM_ADMIN, AUDITOR, CUSTOMER, VENDOR }
