-- Seed Data for Development
-- Default Branch
INSERT INTO BRANCH (BRANCH_CODE, BRANCH_NAME, BRANCH_TYPE, REGION, ZONE, ADDRESS, CITY, STATE, PIN_CODE, IS_ACTIVE, CREATED_BY)
VALUES ('HO001', 'Head Office Mumbai', 'HEAD_OFFICE', 'WESTERN', 'MUMBAI', 'Bandra Kurla Complex', 'Mumbai', 'Maharashtra', '400051', 1, 'SYSTEM');

INSERT INTO BRANCH (BRANCH_CODE, BRANCH_NAME, BRANCH_TYPE, REGION, ZONE, ADDRESS, CITY, STATE, PIN_CODE, IS_ACTIVE, CREATED_BY)
VALUES ('BR001', 'Andheri Branch', 'BRANCH', 'WESTERN', 'MUMBAI', 'Andheri West', 'Mumbai', 'Maharashtra', '400058', 1, 'SYSTEM');

INSERT INTO BRANCH (BRANCH_CODE, BRANCH_NAME, BRANCH_TYPE, REGION, ZONE, ADDRESS, CITY, STATE, PIN_CODE, IS_ACTIVE, CREATED_BY)
VALUES ('BR002', 'Connaught Place Branch', 'BRANCH', 'NORTHERN', 'DELHI', 'Connaught Place', 'New Delhi', 'Delhi', '110001', 1, 'SYSTEM');

-- Default Admin User (password: admin123 - BCrypt encoded)
INSERT INTO USER_MASTER (USERNAME, PASSWORD_HASH, EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, BRANCH_CODE, DESIGNATION, IS_ACTIVE, CREATED_BY)
VALUES ('admin', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'EMP001', 'System', 'Administrator', 'admin@hlms.com', 'HO001', 'System Administrator', 1, 'SYSTEM');

INSERT INTO USER_MASTER (USERNAME, PASSWORD_HASH, EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, BRANCH_CODE, DESIGNATION, IS_ACTIVE, CREATED_BY)
VALUES ('branchmanager', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'EMP002', 'Rajesh', 'Kumar', 'rajesh.kumar@hlms.com', 'BR001', 'Branch Manager', 1, 'SYSTEM');

INSERT INTO USER_MASTER (USERNAME, PASSWORD_HASH, EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, BRANCH_CODE, DESIGNATION, IS_ACTIVE, CREATED_BY)
VALUES ('creditofficer', '$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy', 'EMP003', 'Priya', 'Sharma', 'priya.sharma@hlms.com', 'BR001', 'Credit Officer', 1, 'SYSTEM');

-- Default Roles
INSERT INTO USER_ROLE (USER_ID, ROLE_NAME, ASSIGNED_DATE, ASSIGNED_BY, IS_ACTIVE, CREATED_BY)
VALUES (1, 'SYSTEM_ADMIN', SYSDATE, 'SYSTEM', 1, 'SYSTEM');

INSERT INTO USER_ROLE (USER_ID, ROLE_NAME, ASSIGNED_DATE, ASSIGNED_BY, IS_ACTIVE, CREATED_BY)
VALUES (2, 'BRANCH_MANAGER', SYSDATE, 'SYSTEM', 1, 'SYSTEM');

INSERT INTO USER_ROLE (USER_ID, ROLE_NAME, ASSIGNED_DATE, ASSIGNED_BY, IS_ACTIVE, CREATED_BY)
VALUES (3, 'CREDIT_OFFICER', SYSDATE, 'SYSTEM', 1, 'SYSTEM');

-- Role Permissions
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('SYSTEM_ADMIN', 'MANAGE_USERS', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('SYSTEM_ADMIN', 'MANAGE_ROLES', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('SYSTEM_ADMIN', 'MANAGE_BRANCHES', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('SYSTEM_ADMIN', 'MANAGE_PRODUCTS', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('SYSTEM_ADMIN', 'VIEW_AUDIT_LOG', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('SYSTEM_ADMIN', 'VIEW_REPORTS', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('SYSTEM_ADMIN', 'MANAGE_SYSTEM_PARAMS', 1, 'SYSTEM');

INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('BRANCH_MANAGER', 'VIEW_APPLICATIONS', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('BRANCH_MANAGER', 'APPROVE_LOAN', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('BRANCH_MANAGER', 'APPROVE_DISBURSEMENT', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('BRANCH_MANAGER', 'VIEW_COLLECTIONS', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('BRANCH_MANAGER', 'VIEW_REPORTS', 1, 'SYSTEM');

INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('CREDIT_OFFICER', 'CREATE_APPLICATION', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('CREDIT_OFFICER', 'VIEW_APPLICATIONS', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('CREDIT_OFFICER', 'INITIATE_CREDIT_CHECK', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('CREDIT_OFFICER', 'RECOMMEND_LOAN', 1, 'SYSTEM');
INSERT INTO ROLE_PERMISSION (ROLE_NAME, PERMISSION_NAME, IS_ACTIVE, CREATED_BY) VALUES ('CREDIT_OFFICER', 'MANAGE_DOCUMENTS', 1, 'SYSTEM');

-- Authority Matrix
INSERT INTO AUTHORITY_MATRIX (ROLE_NAME, ACTION_TYPE, MIN_AMOUNT, MAX_AMOUNT, REQUIRES_COMMITTEE, IS_ACTIVE, CREATED_BY)
VALUES ('BRANCH_MANAGER', 'LOAN_APPROVAL', 0, 2500000, 0, 1, 'SYSTEM');

INSERT INTO AUTHORITY_MATRIX (ROLE_NAME, ACTION_TYPE, MIN_AMOUNT, MAX_AMOUNT, REQUIRES_COMMITTEE, IS_ACTIVE, CREATED_BY)
VALUES ('REGIONAL_MANAGER', 'LOAN_APPROVAL', 2500001, 10000000, 0, 1, 'SYSTEM');

INSERT INTO AUTHORITY_MATRIX (ROLE_NAME, ACTION_TYPE, MIN_AMOUNT, MAX_AMOUNT, REQUIRES_COMMITTEE, IS_ACTIVE, CREATED_BY)
VALUES ('ZONAL_MANAGER', 'LOAN_APPROVAL', 10000001, 50000000, 0, 1, 'SYSTEM');

INSERT INTO AUTHORITY_MATRIX (ROLE_NAME, ACTION_TYPE, MIN_AMOUNT, MAX_AMOUNT, REQUIRES_COMMITTEE, IS_ACTIVE, CREATED_BY)
VALUES ('CENTRAL_COMMITTEE', 'LOAN_APPROVAL', 50000001, 9999999999, 1, 1, 'SYSTEM');

-- Default Loan Products
INSERT INTO LOAN_PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT, MIN_TENURE_MONTHS, MAX_TENURE_MONTHS, BASE_INTEREST_RATE, PROCESSING_FEE_PERCENT, MAX_LTV_RATIO, MAX_FOIR, MIN_CIBIL_SCORE, IS_ACTIVE, CREATED_BY)
VALUES ('HL001', 'Home Loan - Salaried', 'HOME_LOAN', 500000, 100000000, 12, 360, 8.50, 0.50, 90.00, 50.00, 650, 1, 'SYSTEM');

INSERT INTO LOAN_PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT, MIN_TENURE_MONTHS, MAX_TENURE_MONTHS, BASE_INTEREST_RATE, PROCESSING_FEE_PERCENT, MAX_LTV_RATIO, MAX_FOIR, MIN_CIBIL_SCORE, IS_ACTIVE, CREATED_BY)
VALUES ('HL002', 'Home Loan - Self Employed', 'HOME_LOAN', 500000, 75000000, 12, 240, 9.00, 0.50, 80.00, 45.00, 700, 1, 'SYSTEM');

INSERT INTO LOAN_PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT, MIN_TENURE_MONTHS, MAX_TENURE_MONTHS, BASE_INTEREST_RATE, PROCESSING_FEE_PERCENT, MAX_LTV_RATIO, MAX_FOIR, MIN_CIBIL_SCORE, IS_ACTIVE, CREATED_BY)
VALUES ('HL003', 'Home Loan - Balance Transfer', 'BALANCE_TRANSFER', 1000000, 100000000, 12, 360, 8.25, 0.25, 85.00, 50.00, 700, 1, 'SYSTEM');

INSERT INTO LOAN_PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT, MIN_TENURE_MONTHS, MAX_TENURE_MONTHS, BASE_INTEREST_RATE, PROCESSING_FEE_PERCENT, MAX_LTV_RATIO, MAX_FOIR, MIN_CIBIL_SCORE, IS_ACTIVE, CREATED_BY)
VALUES ('LAP001', 'Loan Against Property', 'LOAN_AGAINST_PROPERTY', 500000, 50000000, 12, 180, 9.50, 1.00, 60.00, 50.00, 700, 1, 'SYSTEM');

INSERT INTO LOAN_PRODUCT (PRODUCT_CODE, PRODUCT_NAME, PRODUCT_TYPE, MIN_LOAN_AMOUNT, MAX_LOAN_AMOUNT, MIN_TENURE_MONTHS, MAX_TENURE_MONTHS, BASE_INTEREST_RATE, PROCESSING_FEE_PERCENT, MAX_LTV_RATIO, MAX_FOIR, MIN_CIBIL_SCORE, IS_ACTIVE, CREATED_BY)
VALUES ('PMAY001', 'PMAY Home Loan', 'PMAY', 300000, 35000000, 12, 360, 6.50, 0.00, 90.00, 55.00, 600, 1, 'SYSTEM');

-- System Parameters
INSERT INTO SYSTEM_PARAMETER (PARAM_KEY, PARAM_VALUE, PARAM_TYPE, DESCRIPTION, MODULE, IS_ACTIVE, CREATED_BY)
VALUES ('MAX_FOIR_SALARIED', '50', 'NUMBER', 'Maximum FOIR for salaried customers (%)', 'LOAN', 1, 'SYSTEM');

INSERT INTO SYSTEM_PARAMETER (PARAM_KEY, PARAM_VALUE, PARAM_TYPE, DESCRIPTION, MODULE, IS_ACTIVE, CREATED_BY)
VALUES ('MAX_FOIR_SELF_EMPLOYED', '45', 'NUMBER', 'Maximum FOIR for self-employed customers (%)', 'LOAN', 1, 'SYSTEM');

INSERT INTO SYSTEM_PARAMETER (PARAM_KEY, PARAM_VALUE, PARAM_TYPE, DESCRIPTION, MODULE, IS_ACTIVE, CREATED_BY)
VALUES ('NPA_DPD_THRESHOLD', '90', 'NUMBER', 'DPD threshold for NPA classification', 'COLLECTION', 1, 'SYSTEM');

INSERT INTO SYSTEM_PARAMETER (PARAM_KEY, PARAM_VALUE, PARAM_TYPE, DESCRIPTION, MODULE, IS_ACTIVE, CREATED_BY)
VALUES ('SANCTION_VALIDITY_DAYS', '180', 'NUMBER', 'Sanction letter validity in days', 'LOAN', 1, 'SYSTEM');

INSERT INTO SYSTEM_PARAMETER (PARAM_KEY, PARAM_VALUE, PARAM_TYPE, DESCRIPTION, MODULE, IS_ACTIVE, CREATED_BY)
VALUES ('DOCUMENT_RETURN_PENALTY_PER_DAY', '5000', 'NUMBER', 'Penalty per day for delayed document return (INR)', 'SERVICING', 1, 'SYSTEM');

INSERT INTO SYSTEM_PARAMETER (PARAM_KEY, PARAM_VALUE, PARAM_TYPE, DESCRIPTION, MODULE, IS_ACTIVE, CREATED_BY)
VALUES ('CIBIL_REFRESH_DAYS', '30', 'NUMBER', 'Days after which CIBIL score should be refreshed', 'LOAN', 1, 'SYSTEM');

COMMIT;
