-- Customer Master Tables
CREATE SEQUENCE SEQ_CUSTOMER_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE CUSTOMER (
    CUSTOMER_ID NUMBER(19) DEFAULT SEQ_CUSTOMER_ID.NEXTVAL PRIMARY KEY,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    MIDDLE_NAME VARCHAR2(100),
    LAST_NAME VARCHAR2(100) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    GENDER VARCHAR2(10) NOT NULL,
    MARITAL_STATUS VARCHAR2(20),
    CUSTOMER_TYPE VARCHAR2(20) NOT NULL,
    CUSTOMER_CATEGORY VARCHAR2(30),
    RESIDENT_STATUS VARCHAR2(20) NOT NULL,
    PAN_NUMBER VARCHAR2(255),
    AADHAAR_NUMBER VARCHAR2(255),
    EMAIL VARCHAR2(100),
    MOBILE_NUMBER VARCHAR2(15) NOT NULL,
    ALTERNATE_MOBILE VARCHAR2(15),
    NATIONALITY VARCHAR2(50) DEFAULT 'INDIAN',
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE SEQ_CUSTOMER_ADDRESS_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE CUSTOMER_ADDRESS (
    ADDRESS_ID NUMBER(19) DEFAULT SEQ_CUSTOMER_ADDRESS_ID.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    ADDRESS_TYPE VARCHAR2(20) NOT NULL,
    ADDRESS_LINE1 VARCHAR2(200) NOT NULL,
    ADDRESS_LINE2 VARCHAR2(200),
    CITY VARCHAR2(100) NOT NULL,
    STATE VARCHAR2(100) NOT NULL,
    PIN_CODE VARCHAR2(10) NOT NULL,
    COUNTRY VARCHAR2(50) DEFAULT 'INDIA',
    RESIDING_SINCE DATE,
    IS_CURRENT NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CUST_ADDR_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE SEQUENCE SEQ_CUSTOMER_EMPLOYMENT_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE CUSTOMER_EMPLOYMENT (
    EMPLOYMENT_ID NUMBER(19) DEFAULT SEQ_CUSTOMER_EMPLOYMENT_ID.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    EMPLOYMENT_TYPE VARCHAR2(30) NOT NULL,
    EMPLOYER_NAME VARCHAR2(200),
    DESIGNATION VARCHAR2(100),
    EMPLOYEE_ID VARCHAR2(50),
    WORK_EXPERIENCE_YEARS NUMBER(5,1),
    CURRENT_EMPLOYER_YEARS NUMBER(5,1),
    OFFICE_ADDRESS VARCHAR2(500),
    OFFICE_PHONE VARCHAR2(15),
    IS_CURRENT NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CUST_EMP_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE SEQUENCE SEQ_CUSTOMER_INCOME_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE CUSTOMER_INCOME (
    INCOME_ID NUMBER(19) DEFAULT SEQ_CUSTOMER_INCOME_ID.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    INCOME_SOURCE VARCHAR2(30) NOT NULL,
    GROSS_MONTHLY_INCOME NUMBER(15,2) NOT NULL,
    NET_MONTHLY_INCOME NUMBER(15,2) NOT NULL,
    ANNUAL_INCOME NUMBER(15,2),
    INCOME_PROOF_DOCUMENT VARCHAR2(100),
    VERIFIED NUMBER(1) DEFAULT 0,
    VERIFIED_BY VARCHAR2(50),
    VERIFIED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CUST_INC_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE SEQUENCE SEQ_CUSTOMER_KYC_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE CUSTOMER_KYC (
    KYC_ID NUMBER(19) DEFAULT SEQ_CUSTOMER_KYC_ID.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    KYC_TYPE VARCHAR2(30) NOT NULL,
    DOCUMENT_NUMBER VARCHAR2(255) NOT NULL,
    DOCUMENT_FILE_PATH VARCHAR2(500),
    EXPIRY_DATE DATE,
    VERIFICATION_STATUS VARCHAR2(20) DEFAULT 'PENDING',
    VERIFIED_BY VARCHAR2(50),
    VERIFIED_DATE TIMESTAMP,
    REMARKS VARCHAR2(500),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CUST_KYC_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE SEQUENCE SEQ_CUSTOMER_BANK_ACCOUNT_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE CUSTOMER_BANK_ACCOUNT (
    BANK_ACCOUNT_ID NUMBER(19) DEFAULT SEQ_CUSTOMER_BANK_ACCOUNT_ID.NEXTVAL PRIMARY KEY,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    BANK_NAME VARCHAR2(100) NOT NULL,
    BRANCH_NAME VARCHAR2(100),
    ACCOUNT_NUMBER VARCHAR2(255) NOT NULL,
    IFSC_CODE VARCHAR2(11) NOT NULL,
    ACCOUNT_TYPE VARCHAR2(20) NOT NULL,
    IS_PRIMARY NUMBER(1) DEFAULT 0,
    ACCOUNT_HOLDER_NAME VARCHAR2(200),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CUST_BANK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);
