-- Loan Product and Application Tables
CREATE SEQUENCE SEQ_LOAN_PRODUCT_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_PRODUCT (
    PRODUCT_ID NUMBER(19) DEFAULT SEQ_LOAN_PRODUCT_ID.NEXTVAL PRIMARY KEY,
    PRODUCT_CODE VARCHAR2(20) NOT NULL UNIQUE,
    PRODUCT_NAME VARCHAR2(200) NOT NULL,
    PRODUCT_TYPE VARCHAR2(30) NOT NULL,
    MIN_LOAN_AMOUNT NUMBER(15,2) NOT NULL,
    MAX_LOAN_AMOUNT NUMBER(15,2) NOT NULL,
    MIN_TENURE_MONTHS NUMBER(5) NOT NULL,
    MAX_TENURE_MONTHS NUMBER(5) NOT NULL,
    BASE_INTEREST_RATE NUMBER(8,4) NOT NULL,
    PROCESSING_FEE_PERCENT NUMBER(5,2),
    MAX_LTV_RATIO NUMBER(5,2),
    MAX_FOIR NUMBER(5,2),
    MIN_CIBIL_SCORE NUMBER(5),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE SEQ_LOAN_INTEREST_RATE_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_INTEREST_RATE (
    RATE_ID NUMBER(19) DEFAULT SEQ_LOAN_INTEREST_RATE_ID.NEXTVAL PRIMARY KEY,
    PRODUCT_ID NUMBER(19) NOT NULL,
    RATE_TYPE VARCHAR2(20) NOT NULL,
    BASE_RATE NUMBER(8,4) NOT NULL,
    SPREAD NUMBER(8,4) DEFAULT 0,
    EFFECTIVE_RATE NUMBER(8,4) NOT NULL,
    EFFECTIVE_FROM DATE NOT NULL,
    EFFECTIVE_TO DATE,
    SLAB_MIN_AMOUNT NUMBER(15,2),
    SLAB_MAX_AMOUNT NUMBER(15,2),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_RATE_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES LOAN_PRODUCT(PRODUCT_ID)
);

CREATE SEQUENCE SEQ_LOAN_APPLICATION_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_APPLICATION (
    APPLICATION_ID NUMBER(19) DEFAULT SEQ_LOAN_APPLICATION_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_NUMBER VARCHAR2(20) NOT NULL UNIQUE,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    PRODUCT_ID NUMBER(19) NOT NULL,
    BRANCH_CODE VARCHAR2(10) NOT NULL,
    CHANNEL VARCHAR2(20) NOT NULL,
    APPLICATION_STATUS VARCHAR2(30) NOT NULL,
    LOAN_STATUS VARCHAR2(40) NOT NULL,
    REQUESTED_AMOUNT NUMBER(15,2) NOT NULL,
    APPROVED_AMOUNT NUMBER(15,2),
    LOAN_PURPOSE VARCHAR2(30),
    REQUESTED_TENURE_MONTHS NUMBER(5) NOT NULL,
    APPROVED_TENURE_MONTHS NUMBER(5),
    INTEREST_RATE NUMBER(8,4),
    RATE_TYPE VARCHAR2(20),
    EMI_AMOUNT NUMBER(15,2),
    PROCESSING_FEE NUMBER(15,2),
    ASSIGNED_TO VARCHAR2(50),
    SUBMITTED_DATE TIMESTAMP,
    SANCTIONED_DATE TIMESTAMP,
    SANCTIONED_BY VARCHAR2(50),
    REJECTED_DATE TIMESTAMP,
    REJECTION_REASON VARCHAR2(500),
    REMARKS VARCHAR2(1000),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_APP_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_APP_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES LOAN_PRODUCT(PRODUCT_ID)
);

CREATE SEQUENCE SEQ_CO_APPLICANT_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE CO_APPLICANT (
    CO_APPLICANT_ID NUMBER(19) DEFAULT SEQ_CO_APPLICANT_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    CO_APPLICANT_TYPE VARCHAR2(20) NOT NULL,
    RELATIONSHIP_TYPE VARCHAR2(30) NOT NULL,
    INCOME_CONSIDERED NUMBER(1) DEFAULT 0,
    INCOME_WEIGHTAGE NUMBER(5,2),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_COAPP_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID),
    CONSTRAINT FK_COAPP_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE SEQUENCE SEQ_LOAN_DOCUMENT_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_DOCUMENT (
    DOCUMENT_ID NUMBER(19) DEFAULT SEQ_LOAN_DOCUMENT_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    DOCUMENT_TYPE VARCHAR2(30) NOT NULL,
    DOCUMENT_STATUS VARCHAR2(20) NOT NULL,
    FILE_NAME VARCHAR2(200) NOT NULL,
    FILE_PATH VARCHAR2(500) NOT NULL,
    CONTENT_TYPE VARCHAR2(100),
    FILE_SIZE NUMBER(15),
    UPLOADED_BY VARCHAR2(50),
    UPLOADED_DATE TIMESTAMP,
    VERIFIED_BY VARCHAR2(50),
    VERIFIED_DATE TIMESTAMP,
    REJECTION_REASON VARCHAR2(500),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_DOC_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);

CREATE SEQUENCE SEQ_LOAN_CREDIT_CHECK_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_CREDIT_CHECK (
    CREDIT_CHECK_ID NUMBER(19) DEFAULT SEQ_LOAN_CREDIT_CHECK_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    CREDIT_BUREAU VARCHAR2(20) NOT NULL,
    CREDIT_SCORE NUMBER(5),
    REPORT_DATE TIMESTAMP,
    REPORT_REFERENCE VARCHAR2(100),
    REPORT_FILE_PATH VARCHAR2(500),
    EXISTING_LOAN_COUNT NUMBER(5),
    EXISTING_EMI_TOTAL NUMBER(15,2),
    DELINQUENCY_FLAG NUMBER(1) DEFAULT 0,
    DPD_LAST_12_MONTHS NUMBER(5),
    STATUS VARCHAR2(20) NOT NULL,
    REMARKS VARCHAR2(500),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CC_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID),
    CONSTRAINT FK_CC_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID)
);

CREATE SEQUENCE SEQ_LOAN_ELIGIBILITY_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_ELIGIBILITY (
    ELIGIBILITY_ID NUMBER(19) DEFAULT SEQ_LOAN_ELIGIBILITY_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    TOTAL_MONTHLY_INCOME NUMBER(15,2),
    EXISTING_OBLIGATIONS NUMBER(15,2),
    FOIR NUMBER(8,4),
    ELIGIBLE_EMI NUMBER(15,2),
    ELIGIBLE_AMOUNT NUMBER(15,2),
    LTV_RATIO NUMBER(8,4),
    ELIGIBLE_BASED_ON_LTV NUMBER(15,2),
    FINAL_ELIGIBLE_AMOUNT NUMBER(15,2),
    CALCULATION_DATE TIMESTAMP,
    REMARKS VARCHAR2(500),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_ELIG_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);

CREATE SEQUENCE SEQ_LOAN_SANCTION_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_SANCTION (
    SANCTION_ID NUMBER(19) DEFAULT SEQ_LOAN_SANCTION_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    SANCTION_LETTER_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
    SANCTIONED_AMOUNT NUMBER(15,2) NOT NULL,
    SANCTIONED_TENURE_MONTHS NUMBER(5) NOT NULL,
    INTEREST_RATE NUMBER(8,4) NOT NULL,
    RATE_TYPE VARCHAR2(20) NOT NULL,
    EMI_AMOUNT NUMBER(15,2) NOT NULL,
    PROCESSING_FEE NUMBER(15,2),
    SANCTION_DATE DATE NOT NULL,
    VALIDITY_DATE DATE NOT NULL,
    CONDITIONS VARCHAR2(2000),
    SANCTIONED_BY VARCHAR2(50) NOT NULL,
    SANCTION_LETTER_PATH VARCHAR2(500),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_SANC_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);

CREATE SEQUENCE SEQ_LOAN_DEVIATION_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_DEVIATION (
    DEVIATION_ID NUMBER(19) DEFAULT SEQ_LOAN_DEVIATION_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    DEVIATION_TYPE VARCHAR2(50) NOT NULL,
    SEVERITY VARCHAR2(20) NOT NULL,
    DESCRIPTION VARCHAR2(500) NOT NULL,
    JUSTIFICATION VARCHAR2(500),
    APPROVED NUMBER(1) DEFAULT 0,
    APPROVED_BY VARCHAR2(50),
    APPROVED_DATE TIMESTAMP,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_DEV_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);

CREATE SEQUENCE SEQ_LOAN_APPROVAL_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_APPROVAL_WORKFLOW (
    APPROVAL_ID NUMBER(19) DEFAULT SEQ_LOAN_APPROVAL_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    APPROVAL_LEVEL VARCHAR2(30) NOT NULL,
    APPROVER_ROLE VARCHAR2(30) NOT NULL,
    APPROVER_USER_ID VARCHAR2(50),
    ACTION VARCHAR2(20) NOT NULL,
    COMMENTS VARCHAR2(1000),
    ACTION_DATE TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_APPR_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);
