-- Property and Valuation Tables
CREATE SEQUENCE SEQ_PROPERTY_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE PROPERTY (
    PROPERTY_ID NUMBER(19) DEFAULT SEQ_PROPERTY_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    PROPERTY_TYPE VARCHAR2(30) NOT NULL,
    CONSTRUCTION_STATUS VARCHAR2(30) NOT NULL,
    ADDRESS_LINE1 VARCHAR2(200) NOT NULL,
    ADDRESS_LINE2 VARCHAR2(200),
    CITY VARCHAR2(100) NOT NULL,
    STATE VARCHAR2(100) NOT NULL,
    PIN_CODE VARCHAR2(10) NOT NULL,
    SURVEY_NUMBER VARCHAR2(100),
    PLOT_AREA NUMBER(10,2),
    BUILT_UP_AREA NUMBER(10,2),
    CARPET_AREA NUMBER(10,2),
    PROPERTY_AGE_YEARS NUMBER(5),
    BUILDER_NAME VARCHAR2(200),
    PROJECT_NAME VARCHAR2(200),
    IS_APPROVED_PROJECT NUMBER(1) DEFAULT 0,
    RERA_NUMBER VARCHAR2(50),
    EXPECTED_COMPLETION_DATE DATE,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_PROP_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);

CREATE SEQUENCE SEQ_PROPERTY_VALUATION_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE PROPERTY_VALUATION (
    VALUATION_ID NUMBER(19) DEFAULT SEQ_PROPERTY_VALUATION_ID.NEXTVAL PRIMARY KEY,
    PROPERTY_ID NUMBER(19) NOT NULL,
    VALUATION_TYPE VARCHAR2(20) NOT NULL,
    VALUATION_STATUS VARCHAR2(20) NOT NULL,
    VALUATOR_NAME VARCHAR2(200),
    VALUATOR_LICENSE VARCHAR2(50),
    VALUATION_DATE DATE,
    FAIR_MARKET_VALUE NUMBER(15,2),
    FORCED_SALE_VALUE NUMBER(15,2),
    DISTRESS_VALUE NUMBER(15,2),
    GUIDELINE_VALUE NUMBER(15,2),
    REMARKS VARCHAR2(1000),
    REPORT_FILE_PATH VARCHAR2(500),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_VAL_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID)
);

CREATE SEQUENCE SEQ_PROPERTY_LEGAL_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE PROPERTY_LEGAL_OPINION (
    LEGAL_ID NUMBER(19) DEFAULT SEQ_PROPERTY_LEGAL_ID.NEXTVAL PRIMARY KEY,
    PROPERTY_ID NUMBER(19) NOT NULL,
    LAWYER_NAME VARCHAR2(200),
    LAWYER_LICENSE VARCHAR2(50),
    OPINION_DATE DATE,
    TITLE_STATUS VARCHAR2(20) NOT NULL,
    TITLE_CLEAR NUMBER(1) DEFAULT 0,
    ENCUMBRANCE_CHECK NUMBER(1) DEFAULT 0,
    ENCUMBRANCE_PERIOD_YEARS NUMBER(5),
    LITIGATION_PENDING NUMBER(1) DEFAULT 0,
    LITIGATION_DETAILS VARCHAR2(1000),
    RECOMMENDATIONS VARCHAR2(1000),
    REPORT_FILE_PATH VARCHAR2(500),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_LEGAL_PROPERTY FOREIGN KEY (PROPERTY_ID) REFERENCES PROPERTY(PROPERTY_ID)
);
