-- Disbursement, Agreement, CERSAI, NACH, Insurance Tables
CREATE SEQUENCE SEQ_LOAN_AGREEMENT_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_AGREEMENT (
    AGREEMENT_ID NUMBER(19) DEFAULT SEQ_LOAN_AGREEMENT_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    AGREEMENT_NUMBER VARCHAR2(50) NOT NULL UNIQUE,
    AGREEMENT_STATUS VARCHAR2(20) NOT NULL,
    AGREEMENT_DATE DATE,
    STAMPING_DATE DATE,
    STAMP_DUTY_AMOUNT NUMBER(15,2),
    ESIGN_REFERENCE VARCHAR2(100),
    ESIGN_DATE TIMESTAMP,
    AGREEMENT_FILE_PATH VARCHAR2(500),
    MOD_REGISTERED NUMBER(1) DEFAULT 0,
    MOD_REGISTRATION_DATE DATE,
    MOD_REGISTRATION_NUMBER VARCHAR2(50),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_AGREE_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);

CREATE SEQUENCE SEQ_LOAN_CERSAI_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_CERSAI (
    CERSAI_ID NUMBER(19) DEFAULT SEQ_LOAN_CERSAI_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    CERSAI_STATUS VARCHAR2(20) NOT NULL,
    REGISTRATION_NUMBER VARCHAR2(100),
    REGISTRATION_DATE TIMESTAMP,
    ASSET_DESCRIPTION VARCHAR2(500),
    CHARGE_AMOUNT NUMBER(15,2),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CERSAI_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);

CREATE SEQUENCE SEQ_LOAN_NACH_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_NACH_MANDATE (
    NACH_ID NUMBER(19) DEFAULT SEQ_LOAN_NACH_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    MANDATE_STATUS VARCHAR2(20) NOT NULL,
    UMRN VARCHAR2(50),
    BANK_ACCOUNT_ID NUMBER(19),
    MAX_AMOUNT NUMBER(15,2) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    FREQUENCY VARCHAR2(20) DEFAULT 'MONTHLY',
    REGISTRATION_DATE TIMESTAMP,
    REJECTION_REASON VARCHAR2(500),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_NACH_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);

CREATE SEQUENCE SEQ_LOAN_INSURANCE_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_INSURANCE (
    INSURANCE_ID NUMBER(19) DEFAULT SEQ_LOAN_INSURANCE_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    INSURANCE_TYPE VARCHAR2(30) NOT NULL,
    PROVIDER_NAME VARCHAR2(200),
    POLICY_NUMBER VARCHAR2(100),
    SUM_INSURED NUMBER(15,2),
    PREMIUM_AMOUNT NUMBER(15,2),
    POLICY_START_DATE DATE,
    POLICY_END_DATE DATE,
    NOMINEE_NAME VARCHAR2(200),
    NOMINEE_RELATIONSHIP VARCHAR2(30),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_INS_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);

CREATE SEQUENCE SEQ_LOAN_DISBURSEMENT_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_DISBURSEMENT (
    DISBURSEMENT_ID NUMBER(19) DEFAULT SEQ_LOAN_DISBURSEMENT_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    DISBURSEMENT_TYPE VARCHAR2(20) NOT NULL,
    DISBURSEMENT_STATUS VARCHAR2(20) NOT NULL,
    TRANCHE_NUMBER NUMBER(5) DEFAULT 1,
    DISBURSEMENT_AMOUNT NUMBER(15,2) NOT NULL,
    DISBURSEMENT_DATE TIMESTAMP,
    UTR_NUMBER VARCHAR2(50),
    BENEFICIARY_NAME VARCHAR2(200),
    BENEFICIARY_ACCOUNT VARCHAR2(255),
    BENEFICIARY_IFSC VARCHAR2(11),
    BENEFICIARY_BANK VARCHAR2(100),
    IS_BALANCE_TRANSFER NUMBER(1) DEFAULT 0,
    BT_LENDER_NAME VARCHAR2(200),
    BT_LOAN_ACCOUNT VARCHAR2(50),
    BT_OUTSTANDING_AMOUNT NUMBER(15,2),
    APPROVED_BY VARCHAR2(50),
    APPROVED_DATE TIMESTAMP,
    REMARKS VARCHAR2(500),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_DISB_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);

CREATE SEQUENCE SEQ_DISBURSEMENT_SCHEDULE_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE DISBURSEMENT_SCHEDULE (
    SCHEDULE_ID NUMBER(19) DEFAULT SEQ_DISBURSEMENT_SCHEDULE_ID.NEXTVAL PRIMARY KEY,
    APPLICATION_ID NUMBER(19) NOT NULL,
    TRANCHE_NUMBER NUMBER(5) NOT NULL,
    PLANNED_AMOUNT NUMBER(15,2) NOT NULL,
    PLANNED_DATE DATE,
    CONDITION_TO_RELEASE VARCHAR2(500),
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_DSCH_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID)
);
