-- Loan Account, Repayment, Transaction Tables
CREATE SEQUENCE SEQ_LOAN_ACCOUNT_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_ACCOUNT (
    ACCOUNT_ID NUMBER(19) DEFAULT SEQ_LOAN_ACCOUNT_ID.NEXTVAL PRIMARY KEY,
    LOAN_ACCOUNT_NUMBER VARCHAR2(20) NOT NULL UNIQUE,
    APPLICATION_ID NUMBER(19) NOT NULL,
    CUSTOMER_ID NUMBER(19) NOT NULL,
    PRODUCT_ID NUMBER(19) NOT NULL,
    BRANCH_CODE VARCHAR2(10) NOT NULL,
    ACCOUNT_STATUS VARCHAR2(30) NOT NULL,
    DISBURSED_AMOUNT NUMBER(15,2) NOT NULL,
    OUTSTANDING_PRINCIPAL NUMBER(15,2) NOT NULL,
    OUTSTANDING_INTEREST NUMBER(15,2) DEFAULT 0,
    OUTSTANDING_PENALTY NUMBER(15,2) DEFAULT 0,
    TOTAL_OUTSTANDING NUMBER(15,2) NOT NULL,
    INTEREST_RATE NUMBER(8,4) NOT NULL,
    RATE_TYPE VARCHAR2(20) NOT NULL,
    EMI_AMOUNT NUMBER(15,2) NOT NULL,
    TENURE_MONTHS NUMBER(5) NOT NULL,
    REMAINING_TENURE NUMBER(5) NOT NULL,
    EMI_START_DATE DATE NOT NULL,
    EMI_END_DATE DATE NOT NULL,
    NEXT_EMI_DATE DATE,
    LAST_PAYMENT_DATE TIMESTAMP,
    LAST_PAYMENT_AMOUNT NUMBER(15,2),
    OVERDUE_AMOUNT NUMBER(15,2) DEFAULT 0,
    DPD NUMBER(5) DEFAULT 0,
    NPA_DATE DATE,
    CLOSURE_DATE TIMESTAMP,
    CLOSURE_TYPE VARCHAR2(20),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_ACCT_APPLICATION FOREIGN KEY (APPLICATION_ID) REFERENCES LOAN_APPLICATION(APPLICATION_ID),
    CONSTRAINT FK_ACCT_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID),
    CONSTRAINT FK_ACCT_PRODUCT FOREIGN KEY (PRODUCT_ID) REFERENCES LOAN_PRODUCT(PRODUCT_ID)
);

CREATE SEQUENCE SEQ_REPAYMENT_SCHEDULE_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE REPAYMENT_SCHEDULE (
    SCHEDULE_ID NUMBER(19) DEFAULT SEQ_REPAYMENT_SCHEDULE_ID.NEXTVAL PRIMARY KEY,
    ACCOUNT_ID NUMBER(19) NOT NULL,
    INSTALLMENT_NUMBER NUMBER(5) NOT NULL,
    DUE_DATE DATE NOT NULL,
    EMI_AMOUNT NUMBER(15,2) NOT NULL,
    PRINCIPAL_COMPONENT NUMBER(15,2) NOT NULL,
    INTEREST_COMPONENT NUMBER(15,2) NOT NULL,
    OPENING_BALANCE NUMBER(15,2) NOT NULL,
    CLOSING_BALANCE NUMBER(15,2) NOT NULL,
    SCHEDULE_STATUS VARCHAR2(20) NOT NULL,
    PAID_AMOUNT NUMBER(15,2) DEFAULT 0,
    PAID_DATE TIMESTAMP,
    PENALTY_AMOUNT NUMBER(15,2) DEFAULT 0,
    WAIVER_AMOUNT NUMBER(15,2) DEFAULT 0,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_REPAY_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID)
);

CREATE SEQUENCE SEQ_LOAN_TRANSACTION_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_TRANSACTION (
    TRANSACTION_ID NUMBER(19) DEFAULT SEQ_LOAN_TRANSACTION_ID.NEXTVAL PRIMARY KEY,
    ACCOUNT_ID NUMBER(19) NOT NULL,
    TRANSACTION_TYPE VARCHAR2(30) NOT NULL,
    TRANSACTION_DATE TIMESTAMP NOT NULL,
    AMOUNT NUMBER(15,2) NOT NULL,
    PRINCIPAL_COMPONENT NUMBER(15,2),
    INTEREST_COMPONENT NUMBER(15,2),
    PENALTY_COMPONENT NUMBER(15,2),
    BALANCE_AFTER NUMBER(15,2),
    PAYMENT_MODE VARCHAR2(20),
    REFERENCE_NUMBER VARCHAR2(100),
    NARRATION VARCHAR2(500),
    REVERSAL_OF NUMBER(19),
    IS_REVERSED NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_TXN_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID)
);

CREATE SEQUENCE SEQ_EMI_DUE_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE EMI_DUE (
    EMI_DUE_ID NUMBER(19) DEFAULT SEQ_EMI_DUE_ID.NEXTVAL PRIMARY KEY,
    ACCOUNT_ID NUMBER(19) NOT NULL,
    DUE_DATE DATE NOT NULL,
    EMI_AMOUNT NUMBER(15,2) NOT NULL,
    PRINCIPAL_DUE NUMBER(15,2) NOT NULL,
    INTEREST_DUE NUMBER(15,2) NOT NULL,
    PENALTY_DUE NUMBER(15,2) DEFAULT 0,
    TOTAL_DUE NUMBER(15,2) NOT NULL,
    PAID_AMOUNT NUMBER(15,2) DEFAULT 0,
    WAIVER_AMOUNT NUMBER(15,2) DEFAULT 0,
    STATUS VARCHAR2(20) NOT NULL,
    NACH_PRESENTMENT_DATE TIMESTAMP,
    NACH_RESPONSE_DATE TIMESTAMP,
    NACH_STATUS VARCHAR2(20),
    BOUNCE_REASON VARCHAR2(200),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_EMI_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID)
);

CREATE SEQUENCE SEQ_INTEREST_ACCRUAL_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE INTEREST_ACCRUAL (
    ACCRUAL_ID NUMBER(19) DEFAULT SEQ_INTEREST_ACCRUAL_ID.NEXTVAL PRIMARY KEY,
    ACCOUNT_ID NUMBER(19) NOT NULL,
    ACCRUAL_DATE DATE NOT NULL,
    PRINCIPAL_BALANCE NUMBER(15,2) NOT NULL,
    INTEREST_RATE NUMBER(8,4) NOT NULL,
    DAILY_INTEREST NUMBER(15,6) NOT NULL,
    ACCRUED_INTEREST NUMBER(15,2) NOT NULL,
    IS_POSTED NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_ACCR_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID)
);
