-- Collection, NPA, Restructuring, Closure Tables
CREATE SEQUENCE SEQ_COLLECTION_CASE_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE COLLECTION_CASE (
    CASE_ID NUMBER(19) DEFAULT SEQ_COLLECTION_CASE_ID.NEXTVAL PRIMARY KEY,
    ACCOUNT_ID NUMBER(19) NOT NULL,
    CASE_STATUS VARCHAR2(20) NOT NULL,
    COLLECTION_BUCKET VARCHAR2(30) NOT NULL,
    DPD NUMBER(5) NOT NULL,
    OVERDUE_AMOUNT NUMBER(15,2) NOT NULL,
    TOTAL_OUTSTANDING NUMBER(15,2) NOT NULL,
    ASSIGNED_TO VARCHAR2(50),
    ASSIGNED_DATE TIMESTAMP,
    PRIORITY VARCHAR2(10),
    RESOLUTION_DATE TIMESTAMP,
    RESOLUTION_REMARKS VARCHAR2(1000),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CASE_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID)
);

CREATE SEQUENCE SEQ_COLLECTION_ACTION_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE COLLECTION_ACTION (
    ACTION_ID NUMBER(19) DEFAULT SEQ_COLLECTION_ACTION_ID.NEXTVAL PRIMARY KEY,
    CASE_ID NUMBER(19) NOT NULL,
    ACTION_TYPE VARCHAR2(30) NOT NULL,
    ACTION_DATE TIMESTAMP NOT NULL,
    PERFORMED_BY VARCHAR2(50) NOT NULL,
    CONTACT_PERSON VARCHAR2(200),
    CONTACT_NUMBER VARCHAR2(15),
    OUTCOME VARCHAR2(200),
    PROMISE_TO_PAY_DATE DATE,
    PROMISE_TO_PAY_AMOUNT NUMBER(15,2),
    NEXT_ACTION_DATE DATE,
    REMARKS VARCHAR2(1000),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_ACTION_CASE FOREIGN KEY (CASE_ID) REFERENCES COLLECTION_CASE(CASE_ID)
);

CREATE SEQUENCE SEQ_LOAN_NPA_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_NPA (
    NPA_ID NUMBER(19) DEFAULT SEQ_LOAN_NPA_ID.NEXTVAL PRIMARY KEY,
    ACCOUNT_ID NUMBER(19) NOT NULL,
    NPA_DATE DATE NOT NULL,
    NPA_CATEGORY VARCHAR2(30) NOT NULL,
    COLLECTION_BUCKET VARCHAR2(30) NOT NULL,
    DPD NUMBER(5) NOT NULL,
    OUTSTANDING_AMOUNT NUMBER(15,2) NOT NULL,
    PROVISION_PERCENTAGE NUMBER(8,4) NOT NULL,
    PROVISION_AMOUNT NUMBER(15,2) NOT NULL,
    IS_UPGRADED NUMBER(1) DEFAULT 0,
    UPGRADE_DATE DATE,
    PREVIOUS_CATEGORY VARCHAR2(30),
    CLASSIFICATION_DATE TIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_NPA_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID)
);

CREATE SEQUENCE SEQ_LOAN_RESTRUCTURING_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_RESTRUCTURING (
    RESTRUCTURING_ID NUMBER(19) DEFAULT SEQ_LOAN_RESTRUCTURING_ID.NEXTVAL PRIMARY KEY,
    ACCOUNT_ID NUMBER(19) NOT NULL,
    RESTRUCTURING_TYPE VARCHAR2(30) NOT NULL,
    OLD_EMI_AMOUNT NUMBER(15,2),
    NEW_EMI_AMOUNT NUMBER(15,2),
    OLD_INTEREST_RATE NUMBER(8,4),
    NEW_INTEREST_RATE NUMBER(8,4),
    OLD_TENURE_MONTHS NUMBER(5),
    NEW_TENURE_MONTHS NUMBER(5),
    MORATORIUM_MONTHS NUMBER(5),
    MORATORIUM_START_DATE DATE,
    MORATORIUM_END_DATE DATE,
    APPROVAL_DATE DATE,
    APPROVED_BY VARCHAR2(50),
    EFFECTIVE_DATE DATE NOT NULL,
    REASON VARCHAR2(500),
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_RESTR_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID)
);

CREATE SEQUENCE SEQ_LOAN_CLOSURE_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE LOAN_CLOSURE (
    CLOSURE_ID NUMBER(19) DEFAULT SEQ_LOAN_CLOSURE_ID.NEXTVAL PRIMARY KEY,
    ACCOUNT_ID NUMBER(19) NOT NULL,
    CLOSURE_TYPE VARCHAR2(20) NOT NULL,
    CLOSURE_DATE TIMESTAMP NOT NULL,
    PRINCIPAL_OUTSTANDING NUMBER(15,2),
    INTEREST_OUTSTANDING NUMBER(15,2),
    PENALTY_OUTSTANDING NUMBER(15,2),
    FORECLOSURE_CHARGES NUMBER(15,2),
    TOTAL_SETTLEMENT_AMOUNT NUMBER(15,2),
    AMOUNT_RECEIVED NUMBER(15,2),
    NOC_GENERATED NUMBER(1) DEFAULT 0,
    NOC_DATE TIMESTAMP,
    NOC_FILE_PATH VARCHAR2(500),
    CERSAI_RELEASED NUMBER(1) DEFAULT 0,
    DOCUMENTS_RETURNED NUMBER(1) DEFAULT 0,
    DOCUMENTS_RETURN_DATE DATE,
    LIEN_RELEASED NUMBER(1) DEFAULT 0,
    APPROVED_BY VARCHAR2(50),
    REMARKS VARCHAR2(500),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_CLOSE_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES LOAN_ACCOUNT(ACCOUNT_ID)
);
