-- Admin: Branch, User, Role, Authority, Audit, Notification, System Tables
CREATE SEQUENCE SEQ_BRANCH_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE BRANCH (
    BRANCH_ID NUMBER(19) DEFAULT SEQ_BRANCH_ID.NEXTVAL PRIMARY KEY,
    BRANCH_CODE VARCHAR2(10) NOT NULL UNIQUE,
    BRANCH_NAME VARCHAR2(200) NOT NULL,
    BRANCH_TYPE VARCHAR2(20),
    REGION VARCHAR2(100),
    ZONE VARCHAR2(100),
    ADDRESS VARCHAR2(500),
    CITY VARCHAR2(100),
    STATE VARCHAR2(100),
    PIN_CODE VARCHAR2(10),
    PHONE VARCHAR2(15),
    EMAIL VARCHAR2(100),
    BRANCH_HEAD_ID NUMBER(19),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE SEQ_USER_MASTER_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE USER_MASTER (
    USER_ID NUMBER(19) DEFAULT SEQ_USER_MASTER_ID.NEXTVAL PRIMARY KEY,
    USERNAME VARCHAR2(50) NOT NULL UNIQUE,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    EMPLOYEE_ID VARCHAR2(20) UNIQUE,
    FIRST_NAME VARCHAR2(100) NOT NULL,
    LAST_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    MOBILE VARCHAR2(15),
    BRANCH_CODE VARCHAR2(10),
    DESIGNATION VARCHAR2(100),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    LAST_LOGIN_DATE TIMESTAMP,
    PASSWORD_EXPIRY_DATE DATE,
    FAILED_LOGIN_ATTEMPTS NUMBER(3) DEFAULT 0,
    ACCOUNT_LOCKED NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_USER_BRANCH FOREIGN KEY (BRANCH_CODE) REFERENCES BRANCH(BRANCH_CODE)
);

CREATE SEQUENCE SEQ_USER_ROLE_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE USER_ROLE (
    USER_ROLE_ID NUMBER(19) DEFAULT SEQ_USER_ROLE_ID.NEXTVAL PRIMARY KEY,
    USER_ID NUMBER(19) NOT NULL,
    ROLE_NAME VARCHAR2(30) NOT NULL,
    ASSIGNED_DATE DATE NOT NULL,
    ASSIGNED_BY VARCHAR2(50),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_UR_USER FOREIGN KEY (USER_ID) REFERENCES USER_MASTER(USER_ID)
);

CREATE SEQUENCE SEQ_ROLE_PERMISSION_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE ROLE_PERMISSION (
    ROLE_PERMISSION_ID NUMBER(19) DEFAULT SEQ_ROLE_PERMISSION_ID.NEXTVAL PRIMARY KEY,
    ROLE_NAME VARCHAR2(30) NOT NULL,
    PERMISSION_NAME VARCHAR2(50) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT UQ_ROLE_PERM UNIQUE (ROLE_NAME, PERMISSION_NAME)
);

CREATE SEQUENCE SEQ_AUTHORITY_MATRIX_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE AUTHORITY_MATRIX (
    AUTHORITY_ID NUMBER(19) DEFAULT SEQ_AUTHORITY_MATRIX_ID.NEXTVAL PRIMARY KEY,
    ROLE_NAME VARCHAR2(30) NOT NULL,
    ACTION_TYPE VARCHAR2(30) NOT NULL,
    MIN_AMOUNT NUMBER(15,2),
    MAX_AMOUNT NUMBER(15,2),
    REQUIRES_COMMITTEE NUMBER(1) DEFAULT 0,
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE SEQ_AUDIT_LOG_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE AUDIT_LOG (
    AUDIT_ID NUMBER(19) DEFAULT SEQ_AUDIT_LOG_ID.NEXTVAL PRIMARY KEY,
    USER_ID VARCHAR2(50) NOT NULL,
    ACTION VARCHAR2(50) NOT NULL,
    ENTITY_TYPE VARCHAR2(50) NOT NULL,
    ENTITY_ID VARCHAR2(50),
    OLD_VALUE CLOB,
    NEW_VALUE CLOB,
    IP_ADDRESS VARCHAR2(45),
    USER_AGENT VARCHAR2(500),
    ACTION_TIMESTAMP TIMESTAMP NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE SEQUENCE SEQ_NOTIFICATION_LOG_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE NOTIFICATION_LOG (
    NOTIFICATION_ID NUMBER(19) DEFAULT SEQ_NOTIFICATION_LOG_ID.NEXTVAL PRIMARY KEY,
    NOTIFICATION_TYPE VARCHAR2(20) NOT NULL,
    RECIPIENT VARCHAR2(200) NOT NULL,
    SUBJECT VARCHAR2(500),
    BODY CLOB,
    STATUS VARCHAR2(20) NOT NULL,
    SENT_DATE TIMESTAMP,
    RETRY_COUNT NUMBER(3) DEFAULT 0,
    ERROR_MESSAGE VARCHAR2(500),
    REFERENCE_TYPE VARCHAR2(50),
    REFERENCE_ID VARCHAR2(50),
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE TABLE SYSTEM_PARAMETER (
    PARAM_KEY VARCHAR2(100) PRIMARY KEY,
    PARAM_VALUE VARCHAR2(1000) NOT NULL,
    PARAM_TYPE VARCHAR2(20) DEFAULT 'STRING',
    DESCRIPTION VARCHAR2(500),
    MODULE VARCHAR2(50),
    IS_ACTIVE NUMBER(1) DEFAULT 1,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL
);

CREATE SEQUENCE SEQ_HOLIDAY_CALENDAR_ID START WITH 1 INCREMENT BY 1;

CREATE TABLE HOLIDAY_CALENDAR (
    HOLIDAY_ID NUMBER(19) DEFAULT SEQ_HOLIDAY_CALENDAR_ID.NEXTVAL PRIMARY KEY,
    HOLIDAY_DATE DATE NOT NULL,
    HOLIDAY_NAME VARCHAR2(200) NOT NULL,
    HOLIDAY_TYPE VARCHAR2(20) NOT NULL,
    STATE VARCHAR2(100),
    IS_NATIONAL NUMBER(1) DEFAULT 0,
    CREATED_BY VARCHAR2(50) NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    MODIFIED_BY VARCHAR2(50),
    MODIFIED_DATE TIMESTAMP,
    VERSION NUMBER(10) DEFAULT 0 NOT NULL
);
