-- Additional sequences for batch processing
CREATE SEQUENCE SEQ_BATCH_JOB_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NACH_PRESENTMENT_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CREDIT_REPORT_BATCH_ID START WITH 1 INCREMENT BY 1;
