-- Customer Indexes
CREATE INDEX IDX_CUSTOMER_PAN ON CUSTOMER(PAN_NUMBER);
CREATE INDEX IDX_CUSTOMER_AADHAAR ON CUSTOMER(AADHAAR_NUMBER);
CREATE INDEX IDX_CUSTOMER_MOBILE ON CUSTOMER(MOBILE_NUMBER);
CREATE INDEX IDX_CUST_ADDR_CUSTOMER ON CUSTOMER_ADDRESS(CUSTOMER_ID);
CREATE INDEX IDX_CUST_EMP_CUSTOMER ON CUSTOMER_EMPLOYMENT(CUSTOMER_ID);
CREATE INDEX IDX_CUST_INC_CUSTOMER ON CUSTOMER_INCOME(CUSTOMER_ID);
CREATE INDEX IDX_CUST_KYC_CUSTOMER ON CUSTOMER_KYC(CUSTOMER_ID);
CREATE INDEX IDX_CUST_BANK_CUSTOMER ON CUSTOMER_BANK_ACCOUNT(CUSTOMER_ID);

-- Loan Indexes
CREATE INDEX IDX_APP_NUMBER ON LOAN_APPLICATION(APPLICATION_NUMBER);
CREATE INDEX IDX_APP_CUSTOMER ON LOAN_APPLICATION(CUSTOMER_ID);
CREATE INDEX IDX_APP_STATUS ON LOAN_APPLICATION(LOAN_STATUS);
CREATE INDEX IDX_APP_BRANCH ON LOAN_APPLICATION(BRANCH_CODE);
CREATE INDEX IDX_APP_ASSIGNED ON LOAN_APPLICATION(ASSIGNED_TO);
CREATE INDEX IDX_COAPP_APPLICATION ON CO_APPLICANT(APPLICATION_ID);
CREATE INDEX IDX_DOC_APPLICATION ON LOAN_DOCUMENT(APPLICATION_ID);
CREATE INDEX IDX_CC_APPLICATION ON LOAN_CREDIT_CHECK(APPLICATION_ID);
CREATE INDEX IDX_ELIG_APPLICATION ON LOAN_ELIGIBILITY(APPLICATION_ID);
CREATE INDEX IDX_SANC_APPLICATION ON LOAN_SANCTION(APPLICATION_ID);
CREATE INDEX IDX_DEV_APPLICATION ON LOAN_DEVIATION(APPLICATION_ID);
CREATE INDEX IDX_APPR_APPLICATION ON LOAN_APPROVAL_WORKFLOW(APPLICATION_ID);

-- Property Indexes
CREATE INDEX IDX_PROP_APPLICATION ON PROPERTY(APPLICATION_ID);
CREATE INDEX IDX_VAL_PROPERTY ON PROPERTY_VALUATION(PROPERTY_ID);
CREATE INDEX IDX_LEGAL_PROPERTY ON PROPERTY_LEGAL_OPINION(PROPERTY_ID);

-- Disbursement Indexes
CREATE INDEX IDX_AGREE_APPLICATION ON LOAN_AGREEMENT(APPLICATION_ID);
CREATE INDEX IDX_CERSAI_APPLICATION ON LOAN_CERSAI(APPLICATION_ID);
CREATE INDEX IDX_NACH_APPLICATION ON LOAN_NACH_MANDATE(APPLICATION_ID);
CREATE INDEX IDX_INS_APPLICATION ON LOAN_INSURANCE(APPLICATION_ID);
CREATE INDEX IDX_DISB_APPLICATION ON LOAN_DISBURSEMENT(APPLICATION_ID);
CREATE INDEX IDX_DISB_UTR ON LOAN_DISBURSEMENT(UTR_NUMBER);

-- Servicing Indexes
CREATE INDEX IDX_ACCT_NUMBER ON LOAN_ACCOUNT(LOAN_ACCOUNT_NUMBER);
CREATE INDEX IDX_ACCT_APPLICATION ON LOAN_ACCOUNT(APPLICATION_ID);
CREATE INDEX IDX_ACCT_CUSTOMER ON LOAN_ACCOUNT(CUSTOMER_ID);
CREATE INDEX IDX_ACCT_STATUS ON LOAN_ACCOUNT(ACCOUNT_STATUS);
CREATE INDEX IDX_ACCT_DPD ON LOAN_ACCOUNT(DPD);
CREATE INDEX IDX_REPAY_ACCOUNT ON REPAYMENT_SCHEDULE(ACCOUNT_ID);
CREATE INDEX IDX_REPAY_DUEDATE ON REPAYMENT_SCHEDULE(DUE_DATE);
CREATE INDEX IDX_TXN_ACCOUNT ON LOAN_TRANSACTION(ACCOUNT_ID);
CREATE INDEX IDX_TXN_DATE ON LOAN_TRANSACTION(TRANSACTION_DATE);
CREATE INDEX IDX_EMI_ACCOUNT ON EMI_DUE(ACCOUNT_ID);
CREATE INDEX IDX_EMI_DUEDATE ON EMI_DUE(DUE_DATE);
CREATE INDEX IDX_EMI_STATUS ON EMI_DUE(STATUS);
CREATE INDEX IDX_ACCR_ACCOUNT ON INTEREST_ACCRUAL(ACCOUNT_ID);
CREATE INDEX IDX_ACCR_DATE ON INTEREST_ACCRUAL(ACCRUAL_DATE);

-- Collection Indexes
CREATE INDEX IDX_CASE_ACCOUNT ON COLLECTION_CASE(ACCOUNT_ID);
CREATE INDEX IDX_CASE_STATUS ON COLLECTION_CASE(CASE_STATUS);
CREATE INDEX IDX_CASE_BUCKET ON COLLECTION_CASE(COLLECTION_BUCKET);
CREATE INDEX IDX_CASE_ASSIGNED ON COLLECTION_CASE(ASSIGNED_TO);
CREATE INDEX IDX_ACTION_CASE ON COLLECTION_ACTION(CASE_ID);
CREATE INDEX IDX_NPA_ACCOUNT ON LOAN_NPA(ACCOUNT_ID);
CREATE INDEX IDX_NPA_CATEGORY ON LOAN_NPA(NPA_CATEGORY);
CREATE INDEX IDX_RESTR_ACCOUNT ON LOAN_RESTRUCTURING(ACCOUNT_ID);
CREATE INDEX IDX_CLOSE_ACCOUNT ON LOAN_CLOSURE(ACCOUNT_ID);

-- Admin Indexes
CREATE INDEX IDX_USER_BRANCH ON USER_MASTER(BRANCH_CODE);
CREATE INDEX IDX_USER_ROLE_USER ON USER_ROLE(USER_ID);
CREATE INDEX IDX_ROLE_PERM_ROLE ON ROLE_PERMISSION(ROLE_NAME);
CREATE INDEX IDX_AUDIT_USER ON AUDIT_LOG(USER_ID);
CREATE INDEX IDX_AUDIT_ENTITY ON AUDIT_LOG(ENTITY_TYPE, ENTITY_ID);
CREATE INDEX IDX_AUDIT_TIMESTAMP ON AUDIT_LOG(ACTION_TIMESTAMP);
CREATE INDEX IDX_NOTIF_TYPE ON NOTIFICATION_LOG(NOTIFICATION_TYPE);
CREATE INDEX IDX_NOTIF_REF ON NOTIFICATION_LOG(REFERENCE_TYPE, REFERENCE_ID);
