apiVersion: v1
kind: Service
metadata:
  name: hlms-backend-service
  namespace: hlms
  labels:
    app: hlms-backend
spec:
  type: ClusterIP
  selector:
    app: hlms-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
    - name: actuator
      port: 8081
      targetPort: 8081
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: hlms-backend-nodeport
  namespace: hlms
  labels:
    app: hlms-backend
spec:
  type: NodePort
  selector:
    app: hlms-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
